"""add timestamps and unique email to user

Revision ID: 77281ecbe928
Revises: a9b1cf761692
Create Date: 2026-04-23 09:10:26.196303

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "77281ecbe928"
down_revision: Union[str, Sequence[str], None] = "a9b1cf761692"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("created_at", sa.DateTime(), nullable=True))
    op.add_column("user", sa.Column("updated_at", sa.DateTime(), nullable=True))
    op.add_column("user", sa.Column("deleted_at", sa.DateTime(), nullable=True))
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_column("user", "deleted_at")
    op.drop_column("user", "updated_at")
    op.drop_column("user", "created_at")
    # ### end Alembic commands ###
