"""add_itinerary_table

Revision ID: ca46fa07bb6e
Revises: b7915637273f
Create Date: 2026-05-17 22:22:13.312002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca46fa07bb6e'
down_revision: Union[str, Sequence[str], None] = 'b7915637273f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('itinerary',
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default='CURRENT_TIMESTAMP', nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default='CURRENT_TIMESTAMP', nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trip.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trip_id', 'name', name='uq_itinerary_trip_name')
    )
    with op.batch_alter_table('itinerary', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_itinerary_trip_id'), ['trip_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('itinerary', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_itinerary_trip_id'))

    op.drop_table('itinerary')
    # ### end Alembic commands ###
